export const categories = [
    "Fiction",
    "Non-Fiction",
    "Science Fiction",
    "Fantasy",
    "Mystery",
    "Thriller",
    "Romance",
    "History",
    "Biography",
    "Self-Help",
    "Philosophy",
    "Poetry",
    "Science",
    "Technology",
    "Business",
    "Health",
    "Religion",
    "Art",
    "Cooking",
    "Travel",
    "Children",
    "Comics",
    "Graphic Novels",
    "Education",
    "Sports",
    "Music",
  ];